export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const FETCH_MOVIES_SEARCH = 'FETCH_MOVIES_SEARCH';

export const FETCH_MOVIE_LOADING = 'FETCH_MOVIE_LOADING';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_LOADING = 'FETCH_FAVORITES_LOADING';

export const SET_INPUT_SEARCH = 'SET_INPUT_SEARCH';
export const SET_MOVIES_PAGE = 'SET_MOVIES_PAGE';
export const SET_FAVORITE_MOVIE = 'SET_FAVORITE_MOVIE';
export const SET_FAVORITES_ID = 'SET_FAVORITES_IDS';

export const UPDATE_FAVORITE_LIST = 'UPDATE_FAVORITE_LIST';